framework:
    default_locale: en
    enabled_locales: ['en', 'nl']
    translator:
        enabled: true
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
