App\Entity\ContactPerson:
  attributes:
    id:
      groups: [ 'task' ]
    name:
      groups: [ 'task' ]
    street:
      groups: [ 'task' ]
    zipcode:
      groups: [ 'task' ]
    houseNumber:
      groups: [ 'task' ]
    houseNumberExtension:
      groups: [ 'task' ]
    roomNumber:
      groups: [ 'task' ]
    city:
      groups: [ 'task' ]
    phoneNumber:
      groups: [ 'task' ]
    mobileNumber:
      groups: [ 'task' ]
    emailAddress:
      groups: [ 'task' ]
    notes:
      groups: [ 'task' ]