App\Entity\TaskSet:
  attributes:
    id:
      groups: [ 'taskSet', 'task' ]
    status:
      groups: [ 'taskSet', 'task' ]
    assignee:
      groups: [ 'taskSet', 'task' ]
    planned:
      groups: [ 'taskSet', 'task' ]
    tasks:
      groups: [ 'taskSet' ]