App\Entity\User:
  attributes:
    id:
      groups: [ 'user']
    name:
      groups: [ 'user']
    username:
      groups: [ 'user' ]
    email:
      groups: [ 'user' ]
    roles:
      groups: [ 'user' ]
    password:
      groups: []
    companies:
      groups: ['user']