App\Entity\ContactPerson:
  properties:
    id:
      identifier: true
  operations:
    ApiPlatform\Metadata\Post: ~
    ApiPlatform\Metadata\Patch: ~
    ApiPlatform\Metadata\Delete: ~
    ApiPlatform\Metadata\GetCollection: ~
    ApiPlatform\Metadata\Get: ~

  graphQlOperations:
    create:
      class: ApiPlatform\Metadata\GraphQl\Mutation
    update:
      class: ApiPlatform\Metadata\GraphQl\Mutation
    delete:
      class: ApiPlatform\Metadata\GraphQl\DeleteMutation
    ApiPlatform\Metadata\GraphQl\QueryCollection:
      paginationType: 'page'
    ApiPlatform\Metadata\GraphQl\Query: ~