App\Entity\TaskSet:
  properties:
    id:
      identifier: true
  operations:
    ApiPlatform\Metadata\Post: ~
    ApiPlatform\Metadata\Patch:
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_SET_OPERATIONS"))'
      processor: 'App\StateProcessor\EditTaskSetStateProcessor'
    ApiPlatform\Metadata\Delete: ~
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        groups: [ 'taskSet', 'task' ]
      filters:
        - 'task_set_search_filter'
        - 'App\Filter\TaskSetOrderFilter'
        - 'App\Filter\TaskSetsWithTaskMatchingCriteriaFilter'
        - 'App\Filter\ExcludeTaskSetOfTaskFilter'
        - 'App\Filter\TaskSetStatusFilter'
        - 'App\Filter\TaskSetTaskCompanyFilter'
        - 'App\Filter\TaskSetTaskRegionFilter'
        - 'App\Filter\TaskSetTaskTypeFilter'
        - 'App\Filter\TaskSetAssigneeFilter'
        - 'App\Filter\TaskSetPlannedFilter'
    ApiPlatform\Metadata\Get:
      normalizationContext:
        groups: [ 'taskSet', 'task' ]

  graphQlOperations:
    create:
      class: ApiPlatform\Metadata\GraphQl\Mutation
    update:
      class: ApiPlatform\Metadata\GraphQl\Mutation
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_SET_OPERATIONS"))'
      processor: 'App\StateProcessor\EditTaskSetStateProcessor'
    delete:
      class: ApiPlatform\Metadata\GraphQl\DeleteMutation
    ApiPlatform\Metadata\GraphQl\QueryCollection:
      normalizationContext:
        groups: [ 'taskSet', 'task' ]
      filters:
        - 'task_set_search_filter'
        - 'App\Filter\TaskSetOrderFilter'
        - 'App\Filter\TaskSetsWithTaskMatchingCriteriaFilter'
        - 'App\Filter\ExcludeTaskSetOfTaskFilter'
        - 'App\Filter\TaskSetStatusFilter'
        - 'App\Filter\TaskSetTaskCompanyFilter'
        - 'App\Filter\TaskSetTaskRegionFilter'
        - 'App\Filter\TaskSetTaskTypeFilter'
        - 'App\Filter\TaskSetAssigneeFilter'
        - 'App\Filter\TaskSetPlannedFilter'
      paginationType: 'page'
    ApiPlatform\Metadata\GraphQl\Query:
      normalizationContext:
        groups: [ 'taskSet', 'task' ]