App\Entity\TaskPatchRemove:
  properties:
    id:
      identifier: true
  operations:
    ApiPlatform\Metadata\Post:
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS"))'
      input: 'App\Dto\CreateTaskPatchDto'
      processor: 'App\StateProcessor\CreateTaskPatchRemoveStateProcessor'
    ApiPlatform\Metadata\Patch:
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS")) ||
                  is_granted(constant("App\\Entity\\User::ROLE_ENGINEER"))'
      input: 'App\Dto\EditTaskPatchDto'
      processor: 'App\StateProcessor\EditTaskPatchRemoveStateProcessor'
    ApiPlatform\Metadata\Delete: ~
    ApiPlatform\Metadata\GetCollection:
      filters: [ 'general_order_filter' ]
      normalizationContext:
        groups: [ 'task', 'task-patch-remove' ]
    ApiPlatform\Metadata\Get:
      normalizationContext:
        groups: [ 'task', 'task-patch-remove' ]

  graphQlOperations:
    create:
      class: ApiPlatform\Metadata\GraphQl\Mutation
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS"))'
      input: 'App\Dto\CreateTaskPatchDto'
      processor: 'App\StateProcessor\CreateTaskPatchRemoveStateProcessor'
    update:
      class: ApiPlatform\Metadata\GraphQl\Mutation
      input: 'App\Dto\EditTaskPatchDto'
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS")) ||
                  is_granted(constant("App\\Entity\\User::ROLE_ENGINEER"))'
      processor: 'App\StateProcessor\EditTaskPatchRemoveStateProcessor'
    delete:
      class: ApiPlatform\Metadata\GraphQl\DeleteMutation
    ApiPlatform\Metadata\GraphQl\QueryCollection:
      normalizationContext:
        groups: [ 'task', 'task-patch-remove' ]
      filters: [ 'general_order_filter' ]
      paginationType: 'page'
    ApiPlatform\Metadata\GraphQl\Query:
      normalizationContext:
        groups: [ 'task', 'task-patch-remove' ]