App\Entity\TaskType:
  properties:
    id:
      identifier: true
  operations:
    ApiPlatform\Metadata\Post: ~
    ApiPlatform\Metadata\Patch: ~
    ApiPlatform\Metadata\Delete: ~
    ApiPlatform\Metadata\GetCollection:
      normalizationContext:
        groups: [ 'task' ]
      filters:
        - 'general_order_filter'
        - 'task_type_search_filter'
        - 'App\Filter\TaskTypesWithMatchingCriteriaFilter'
        - 'App\Filter\TaskTypesWithMatchingCriteriaForUserFilter'
    ApiPlatform\Metadata\Get:
      normalizationContext:
        groups: [ 'task' ]

  graphQlOperations:
    create:
      class: ApiPlatform\Metadata\GraphQl\Mutation
    update:
      class: ApiPlatform\Metadata\GraphQl\Mutation
    delete:
      class: ApiPlatform\Metadata\GraphQl\DeleteMutation
    ApiPlatform\Metadata\GraphQl\QueryCollection:
      normalizationContext:
        groups: [ 'task' ]
      filters:
        - 'general_order_filter'
        - 'task_type_search_filter'
        - 'App\Filter\TaskTypesWithMatchingCriteriaFilter'
        - 'App\Filter\TaskTypesWithMatchingCriteriaForUserFilter'
      paginationType: 'page'
    ApiPlatform\Metadata\GraphQl\Query:
      normalizationContext:
        groups: [ 'task' ]