App\Entity\Task:
  properties:
    id:
      identifier: true
  operations:
    ApiPlatform\Metadata\Post:
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS"))'
      input: 'App\Dto\CreateTaskDto'
      processor: 'App\StateProcessor\CreateTaskStateProcessor'
    ApiPlatform\Metadata\Patch:
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS")) 
                  || is_granted(constant("App\\Entity\\User::ROLE_ENGINEER"))'
    ApiPlatform\Metadata\Delete: ~
    ApiPlatform\Metadata\GetCollection:
      filters:
        - 'general_order_filter'
        - 'task_order_filter'
        - 'region_task_search_filter'
        - 'App\Filter\UniqueTaskRegionFilter'
      normalizationContext:
        groups: [ 'task' ]
    ApiPlatform\Metadata\Get:
      normalizationContext:
        groups: [ 'task' ]

    moveTask:
      class: ApiPlatform\Metadata\Patch
      method: PATCH
      uriTemplate: '/tasks/{id}/move'
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS"))'
      input: 'App\Dto\MoveTaskDto'
      read: false
      processor: 'App\StateProcessor\MoveTaskStateProcessor'

    changeStatusTask:
      class: ApiPlatform\Metadata\Patch
      method: PATCH
      uriTemplate: '/tasks/{id}/change_status'
      security: 'is_granted(constant("App\\Entity\\User::ROLE_ENGINEER"))'
      input: 'App\Dto\ChangeTaskStatusDto'
      read: false
      processor: 'App\StateProcessor\ChangeTaskStatusProcessor'

  graphQlOperations:
    create:
      class: ApiPlatform\Metadata\GraphQl\Mutation
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS"))'
      input: 'App\Dto\CreateTaskDto'
      processor: 'App\StateProcessor\CreateTaskStateProcessor'
    update:
      class: ApiPlatform\Metadata\GraphQl\Mutation
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS")) ||
                  is_granted(constant("App\\Entity\\User::ROLE_ENGINEER"))'
    delete:
      class: ApiPlatform\Metadata\GraphQl\DeleteMutation
    ApiPlatform\Metadata\GraphQl\QueryCollection:
      normalizationContext:
        groups: [ 'task' ]
      filters:
        - 'general_order_filter'
        - 'task_order_filter'
        - 'region_task_search_filter'
        - 'App\Filter\UniqueTaskRegionFilter'
      paginationType: 'page'
    ApiPlatform\Metadata\GraphQl\Query:
      normalizationContext:
        groups: [ 'task' ]

    move:
      class: ApiPlatform\Metadata\GraphQl\Mutation
      security: 'is_granted(constant("App\\Entity\\User::ROLE_TASK_OPERATIONS"))'
      input: 'App\Dto\MoveTaskDto'
      read: false
      processor: 'App\StateProcessor\MoveTaskStateProcessor'

    changeStatus:
      class: ApiPlatform\Metadata\GraphQl\Mutation
      security: 'is_granted(constant("App\\Entity\\User::ROLE_ENGINEER"))'
      input: 'App\Dto\ChangeTaskStatusDto'
      read: false
      processor: 'App\StateProcessor\ChangeTaskStatusProcessor'