services:

  general_order_filter:
    parent: 'api_platform.doctrine.orm.order_filter'
    arguments: [ ~ ]
    tags:  [ 'api_platform.filter' ]
    autowire: false
    autoconfigure: false
    public: false

  boolean_filter:
    parent: 'api_platform.doctrine.orm.boolean_filter'
    arguments: [ ~ ]
    tags:  [ 'api_platform.filter' ]
    autowire: false
    autoconfigure: false
    public: false

  user_search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments: [ { name: 'partial' } ]
    tags: [ 'api_platform.filter' ]
    autowire: false
    autoconfigure: false
    public: false