controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_doc:
    path: /api/docs
    controller: api_platform.swagger_ui.action

authentication_token:
    path: /api/token
    methods: [ 'POST' ]

api_refresh_token:
    path: /api/token/refresh
    methods: [ 'POST' ]